name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.5.0'
    - name: Install Dependencies
      run: npm install jest


      # Finally, run our tests
    - name: Run the tests
      run: npm run test
